### ISSUE TITLE
ERROR 'aws' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by CemEntok** [EscVM/OIDv4_ToolKit#106]
_Python 3.7.11 | miniconda Command Prompt | Windows 10_
Hello, I am having a recent error which is given in the title of issue and can be seen in following figure:

![image](https://user-images.githubusercontent.com/97525722/180777225-d2547e11-467d-4024-bb48-c305f4ed4672.png)

It is not downloading images, just creating empty folder and an empty label folder inside of Class folder. How can we solve this issue? Is there anyone who has already faced with this?

Here is the command I am using:

**python main.py downloader --classes Knife --type_csv test --image_IsDepiction 0 --limit 6**

**Comment by zahiriddin-rustamov** [comment]
Dear @CemEntok 

I had the same issue. I believe it was due to the problem with the python version.

I tried with python=3.7.2 ([conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)) and it's working as intended.

Edit (in case I come back here again):
you also need to run `pip install awscli`

**Comment by CemEntok** [comment]
@zahir2000  Thank you! It really works when I have downgraded my Python version from 3.7.11 to 3.7.2.
