### ISSUE TITLE
Only downloads 13 images

### ISSUE THREAD

**Issue by Francisobiagwu** [EscVM/OIDv4_ToolKit#24]
I tried to use the software, but it only downloads 13 images, even though I set the limit to 500

**Comment by ibrhmyzc** [comment]
> The limit option is only if you want to limit the number of downloads. On the other hand, if you want to download all available images you should't use it :) Which class of images are you trying of use?

I have a similar problem too. Knives images are what I am looking for but there are only 150 images of them even though i do not type any limit  option. In this website there are a lot of them available.

**Comment by keldrom** [comment]
@ibrhmyzc could you please share the `command` that you use and maybe a screen of the terminal? Because if you don't put the limit arg for the download the scrips has to download all the possible images.

**Comment by ibrhmyzc** [comment]
> @ibrhmyzc could you please share the `command` that you use and maybe a screen of the terminal? Because if you don't put the limit arg for the download the scrips has to download all the possible images.

 python main.py downloader --classes Knife --type_csv train --limit 10000

**Comment by keldrom** [comment]
![OIDv4_knife](https://user-images.githubusercontent.com/37141579/55338119-458ed580-54a0-11e9-8fae-d81524c193eb.png)
@ibrhmyzc as you can notice I've used the same command as you except for:
- `python3` instead of `python` : if you have only one version installed and it's python3 no problem, if you're trying to use this tools with python2 we've found you're issue;
- `--limit 100` instead of `--limit 1000`, only for avoid to download all those images but as you can notice in the folder I've correctly 100 images.

**Comment by AmitPrajapati1902** [comment]
same happens with me.

![Screenshot 2019-04-02 at 4 41 38 PM](https://user-images.githubusercontent.com/4670121/55398518-5b66ce00-5566-11e9-95da-d587508fbfd4.png)

**Comment by keldrom** [comment]
Guys I think that you don't really know what you're doing (or I'm not able to understand you're problem)
The script takes as argument the limit of images but obviously if online there are fewer images the OIDv4 will download all the available ones.

Online for **VALIDATION** dataset there are 56 images, as is also reported into the screen of @AmitPrajapati1902, so if the limit is set to 10000 the script will download 56 images.
The fact that you said about more available images is because I think you're referring to **train** or **test** dataset.

For the class knife there are 610 images in the **train** dataset, 56 in **validation** and 161 in **test**.

If you wish to download all the available knife images (827) you can use the command:

`python3 main.py downloader --classes Knife --type_csv all`

I will now close this issues, if you will have other problems don't hesitate to contact us.

**Comment by AmitPrajapati1902** [comment]
@keldrom  Yes you right, i understand now, its working fine. thanks lot.
